### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by AntoineAugusti**

### CODE REVIEW

**Comment by abulte** [comment]
Any background on that? :popcorn:

**Comment by AntoineAugusti** [comment]
Sure! Actually, I could use another pair of eyes.

Builds started failing on CircleCI.
- Latest successful: https://circleci.com/gh/etalab/schema.data.gouv.fr/17582
- First red: https://circleci.com/gh/etalab/schema.data.gouv.fr/17584

The reported error is cryptic
```
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

But it seems caused by a dependency. What's strange is that dependencies were not downloaded from the cache, even if the cache key (and the underlying requirements  file) did not change.

- `Found a cache from build 16814 at v1-dependenciesJQr35E8H7HBgiqGqgvbljeCCl__wNu28atBG3ATZAP4=`
- `No cache is found for key: v1-dependencies-JQr35E8H7HBgiqGqgvbljeCCl__wNu28atBG3ATZAP4=`

I guess caches expires after a few weeks on CircleCI. The last one was generated at this point:
```
Skipping cache generation, cache already exists for key: v1-dependencies-JQr35E8H7HBgiqGqgvbljeCCl__wNu28atBG3ATZAP4=
Found one created at 2020-02-07 05:00:54 +0000 UTC
```

So the `requirements.txt` did not change and was locked down to specific minor version, but when downloaded again from PyPi, it fails. At this point, I decided it was strange and upgraded dependencies.

**Comment by abulte** [comment]
Looks like a classical transitive dependency version problem. Pinning `gitdb` should have been enough but upgrading can work too 👌

**Comment by AntoineAugusti** [comment]
gitdb was already specified at a specific minor version 🤔 

`GitPython==3.0.5`

**Comment by abulte** [comment]
gitdb is a requirement of gitpython ;-) https://github.com/gitpython-developers/GitPython/blob/ac286162b577c35ce855a3048c82808b30b217a8/requirements.txt#L1

**Comment by AntoineAugusti** [comment]
Oh thanks. Well, cumbersome to go through all dependencies of your dependencies to catch this.

**Comment by abulte** [comment]
That’s a major problem with python dep management right now, yes.

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by AntoineAugusti** [comment]
Thank you for pointing to this issue @Harmon758!

And thanks for your work as a maintainer of GitPython. Much appreciated. 🙏

**Pull request merged**
